MEDIUMS = [
        "painting",
        "drawing",
        "photograph",
        "HD photo",
        "illustration",
        "portrait",
        "sketch",
        "3d render",
        "digital painting",
        "concept art",
        "screenshot",
        "canvas painting",
        "watercolor art",
        "print",
        "mosaic",
        "sculpture",
        "cartoon",
        "comic art",
        "anime",
    ]

SUBJECTS = [
        "dog",
        "cat",
        "horse",
        "cow",
        "pig",
        "sheep",
        "lion",
        "elephant",
        "monkey",
        "bird",
        "chicken",
        "eagle",
        "parrot",
        "penguin",
        "fish",
        "shark",
        "dolphin",
        "whale",
        "octopus",
        "bee",
        "butterfly",
        "ant",
        "ladybug",
        "person",
        "man",
        "woman",
        "child",
        "baby",
        "boy",
        "girl",
        "car",
        "boat",
        "airplane",
        "bicycle",
        "motorcycle",
        "train",
        "building",
        "house",
        "bridge",
        "castle",
        "temple",
        "monument",
        "tree",
        "flower",
        "mountain",
        "lake",
        "river",
        "ocean",
        "beach",
        "fruit",
        "vegetable",
        "meat",
        "bread",
        "cake",
        "soup",
        "coffee",
        "toy",
        "book",
        "phone",
        "computer",
        "TV",
        "camera",
        "musical instrument",
        "furniture",
        "road",
        "park",
        "garden",
        "forest",
        "city",
        "sunset",
        "clouds",
    ]